.\simc_vs2019.exe .\frost\legendaries.simc
.\simc_vs2019.exe .\frost\legendaries-2-target.simc
.\simc_vs2019.exe .\frost\soulbinds-week-1.simc
.\simc_vs2019.exe .\frost\soulbinds-week-4.simc
.\simc_vs2019.exe .\frost\soulbinds-max.simc
.\simc_vs2019.exe .\frost\races.simc
.\simc_vs2019.exe .\frost\covenant-abilities.simc
.\simc_vs2019.exe .\frost\relics.simc
.\simc_vs2019.exe .\frost\soulbinds-week-4-2-target.simc
.\simc_vs2019.exe .\frost\stats.simc