.\simc.exe .\destruction\legendaries.simc
.\simc.exe .\destruction\legendaries-cov.simc
.\simc.exe .\destruction\soulbinds-16.simc
.\simc.exe .\destruction\soulbinds-25.simc
.\simc.exe .\destruction\soulbinds-22.simc
.\simc.exe .\destruction\soulbinds-max.simc
.\simc.exe .\destruction\races-alli.simc
.\simc.exe .\destruction\races-horde.simc
.\simc.exe .\destruction\covenant-abilities.simc
.\simc.exe .\destruction\relics.simc