.\simc.exe .\frost\legendaries.simc
.\simc.exe .\frost\legendaries-cov.simc
.\simc.exe .\frost\soulbinds-16.simc
.\simc.exe .\frost\soulbinds-22.simc
.\simc.exe .\frost\soulbinds-25.simc
.\simc.exe .\frost\soulbinds-max.simc
.\simc.exe .\frost\races-alli.simc
.\simc.exe .\frost\races-horde.simc
.\simc.exe .\frost\covenant-abilities.simc
.\simc.exe .\frost\relics.simc
.\simc.exe .\frost\trinkets.simc

.\simc.exe .\arcane\legendaries.simc
.\simc.exe .\arcane\legendaries-cov.simc
.\simc.exe .\arcane\soulbinds-16.simc
.\simc.exe .\arcane\soulbinds-22.simc
.\simc.exe .\arcane\soulbinds-25.simc
.\simc.exe .\arcane\soulbinds-max.simc
.\simc.exe .\arcane\races-alli.simc
.\simc.exe .\arcane\races-horde.simc
.\simc.exe .\arcane\covenant-abilities.simc
.\simc.exe .\arcane\relics.simc
.\simc.exe .\arcane\trinkets.simc

.\simc.exe .\fire\legendaries.simc
.\simc.exe .\fire\legendaries-cov.simc
.\simc.exe .\fire\soulbinds-16.simc
.\simc.exe .\fire\soulbinds-22.simc
.\simc.exe .\fire\soulbinds-25.simc
.\simc.exe .\fire\soulbinds-max.simc
.\simc.exe .\fire\races-alli.simc
.\simc.exe .\fire\races-horde.simc
.\simc.exe .\fire\covenant-abilities.simc
.\simc.exe .\fire\relics.simc
.\simc.exe .\fire\trinkets.simc

.\simc.exe .\destruction\legendaries.simc
.\simc.exe .\destruction\legendaries-cov.simc
.\simc.exe .\destruction\soulbinds-16.simc
.\simc.exe .\destruction\soulbinds-25.simc
.\simc.exe .\destruction\soulbinds-22.simc
.\simc.exe .\destruction\soulbinds-max.simc
.\simc.exe .\destruction\races-alli.simc
.\simc.exe .\destruction\races-horde.simc
.\simc.exe .\destruction\covenant-abilities.simc
.\simc.exe .\destruction\relics.simc
.\simc.exe .\destruction\trinkets.simc

.\simc.exe .\affliction\legendaries.simc
.\simc.exe .\affliction\legendaries-cov.simc
.\simc.exe .\affliction\soulbinds-16.simc
.\simc.exe .\affliction\soulbinds-25.simc
.\simc.exe .\affliction\soulbinds-22.simc
.\simc.exe .\affliction\soulbinds-max.simc
.\simc.exe .\affliction\races-alli.simc
.\simc.exe .\affliction\races-horde.simc
.\simc.exe .\affliction\covenant-abilities.simc
.\simc.exe .\affliction\relics.simc
.\simc.exe .\affliction\trinkets.simc