.\simc.exe .\arcane\legendaries.simc
.\simc.exe .\arcane\legendaries-cov.simc
.\simc.exe .\arcane\soulbinds-16.simc
.\simc.exe .\arcane\soulbinds-22.simc
.\simc.exe .\arcane\soulbinds-25.simc
.\simc.exe .\arcane\soulbinds-max.simc
.\simc.exe .\arcane\races-alli.simc
.\simc.exe .\arcane\races-horde.simc
.\simc.exe .\arcane\covenant-abilities.simc
.\simc.exe .\arcane\relics.simc
.\simc.exe .\arcane\trinkets.simc